package com.viewcompose

/** In-process tags owned by the Animation demo fixtures. */
internal object DemoAnimationTestTags {
    const val ANIMATION_VISIBILITY_TOGGLE = "animation_visibility_toggle"
    const val ANIMATION_VISIBILITY_TARGET = "animation_visibility_target"
    const val ANIMATION_VISIBILITY_FOOTER = "animation_visibility_footer"
    const val ANIMATION_TASK_TOGGLE = "animation_task_toggle"
    const val ANIMATION_TASK_STATUS = "animation_task_status"
    const val ANIMATION_TASK_ACTIONS = "animation_task_actions"
    const val ANIMATION_CONTENT_TOGGLE = "animation_content_toggle"
    const val ANIMATION_CONTENT_LABEL = "animation_content_label"
    const val ANIMATION_CROSSFADE_TOGGLE = "animation_crossfade_toggle"
    const val ANIMATION_CROSSFADE_LABEL = "animation_crossfade_label"
    const val ANIMATION_LIST_ADD = "animation_list_add"
    const val ANIMATION_LIST_REORDER = "animation_list_reorder"
    const val ANIMATION_LIST_FIRST = "animation_list_first"
    const val ANIMATION_SPEC_KIND_TOGGLE = "animation_spec_kind_toggle"
    const val ANIMATION_SPEC_TARGET_TOGGLE = "animation_spec_target_toggle"
    const val ANIMATION_SPEC_EASING_TOGGLE = "animation_spec_easing_toggle"
    const val ANIMATION_SPEC_REPEAT_MODE_TOGGLE = "animation_spec_repeat_mode_toggle"
    const val ANIMATION_SPEC_FLOAT_VALUE = "animation_spec_float_value"
    const val ANIMATION_SPEC_INT_VALUE = "animation_spec_int_value"
    const val ANIMATION_SPEC_COLOR_VALUE = "animation_spec_color_value"
    const val ANIMATION_SPEC_DP_VALUE = "animation_spec_dp_value"
    const val ANIMATION_SPEC_VECTOR_TOGGLE = "animation_spec_vector_toggle"
    const val ANIMATION_SPEC_VECTOR_VALUE = "animation_spec_vector_value"
    const val ANIMATION_SPEC_SIZE_TOGGLE = "animation_spec_size_toggle"
    const val ANIMATION_SPEC_SIZE_PROBE = "animation_spec_size_probe"
    const val ANIMATION_TRANSITION_TOGGLE = "animation_transition_toggle"
    const val ANIMATION_TRANSITION_ALPHA = "animation_transition_alpha"
    const val ANIMATION_TRANSITION_INT = "animation_transition_int"
    const val ANIMATION_TRANSITION_DP = "animation_transition_dp"
    const val ANIMATION_TRANSITION_COLOR = "animation_transition_color"
    const val ANIMATION_VISIBILITY_STATE_TOGGLE = "animation_visibility_state_toggle"
    const val ANIMATION_VISIBILITY_STATE_STATUS = "animation_visibility_state_status"
    const val ANIMATION_VISIBILITY_STATE_TARGET = "animation_visibility_state_target"
    const val ANIMATION_ROW_AXIS_TOGGLE = "animation_row_axis_toggle"
    const val ANIMATION_ROW_AXIS_TARGET = "animation_row_axis_target"
    const val ANIMATION_COLUMN_AXIS_TOGGLE = "animation_column_axis_toggle"
    const val ANIMATION_COLUMN_AXIS_TARGET = "animation_column_axis_target"
    const val ANIMATION_INFINITE_RUN_TOGGLE = "animation_infinite_run_toggle"
    const val ANIMATION_INFINITE_REPEAT_MODE = "animation_infinite_repeat_mode"
    const val ANIMATION_INFINITE_VALUE = "animation_infinite_value"
    const val ANIMATION_ANIMATABLE_TO_HIGH = "animation_animatable_to_high"
    const val ANIMATION_ANIMATABLE_TO_LOW = "animation_animatable_to_low"
    const val ANIMATION_ANIMATABLE_DECAY_POSITIVE = "animation_animatable_decay_positive"
    const val ANIMATION_ANIMATABLE_DECAY_NEGATIVE = "animation_animatable_decay_negative"
    const val ANIMATION_ANIMATABLE_SNAP_HIGH = "animation_animatable_snap_high"
    const val ANIMATION_ANIMATABLE_SNAP_LOW = "animation_animatable_snap_low"
    const val ANIMATION_ANIMATABLE_STOP = "animation_animatable_stop"
    const val ANIMATION_ANIMATABLE_VALUE = "animation_animatable_value"
}
