package com.viewcompose

/** In-process tags owned by the Graphics demo fixtures. */
internal object DemoGraphicsTestTags {
    const val GRAPHICS_PRIMITIVES_CANVAS = "graphics_primitives_canvas"
    const val GRAPHICS_PATH_CLIP_CANVAS = "graphics_path_clip_canvas"
    const val GRAPHICS_BLEND_TOGGLE = "graphics_blend_toggle"
    const val GRAPHICS_BLEND_STATUS = "graphics_blend_status"
    const val GRAPHICS_BLEND_CANVAS = "graphics_blend_canvas"
    const val GRAPHICS_DRAW_CONTENT_TOGGLE = "graphics_draw_content_toggle"
    const val GRAPHICS_DRAW_CONTENT_STATUS = "graphics_draw_content_status"
    const val GRAPHICS_DRAW_CONTENT_CANVAS = "graphics_draw_content_canvas"
    const val GRAPHICS_CACHE_KEY_BUMP = "graphics_cache_key_bump"
    const val GRAPHICS_CACHE_STATUS = "graphics_cache_status"
    const val GRAPHICS_CACHE_CANVAS = "graphics_cache_canvas"
    const val GRAPHICS_SHADOW_OUTER_SINGLE = "graphics_shadow_outer_single"
    const val GRAPHICS_SHADOW_OUTER_MULTI = "graphics_shadow_outer_multi"
    const val GRAPHICS_SHADOW_SPREAD_POSITIVE = "graphics_shadow_spread_positive"
    const val GRAPHICS_SHADOW_SPREAD_NEGATIVE = "graphics_shadow_spread_negative"
    const val GRAPHICS_SHADOW_CUT_SHAPE = "graphics_shadow_cut_shape"
    const val GRAPHICS_SHADOW_INNER_SINGLE = "graphics_shadow_inner_single"
    const val GRAPHICS_SHADOW_INNER_MULTI = "graphics_shadow_inner_multi"
    const val GRAPHICS_SHADOW_INNER_INTEROP = "graphics_shadow_inner_interop"
    const val GRAPHICS_SHADOW_INNER_FIELD = "graphics_shadow_inner_field"
    const val GRAPHICS_SHADOW_INNER_CLICK_BUTTON = "graphics_shadow_inner_click_button"
    const val GRAPHICS_SHADOW_INNER_CLICK_COUNT = "graphics_shadow_inner_click_count"
    const val GRAPHICS_SHADOW_POLICY = "graphics_shadow_policy"
    const val GRAPHICS_SHADOW_DIAGNOSTICS_REFRESH = "graphics_shadow_diagnostics_refresh"
    const val GRAPHICS_SHADOW_CACHE_CLEAR = "graphics_shadow_cache_clear"
    const val GRAPHICS_SHADOW_DIAGNOSTIC_SAMPLE = "graphics_shadow_diagnostic_sample"
    const val GRAPHICS_SHADOW_BACKEND_POLICY = "graphics_shadow_backend_policy"
    const val GRAPHICS_SHADOW_BACKEND_ACTUAL = "graphics_shadow_backend_actual"
    const val GRAPHICS_SHADOW_CACHE_HITS = "graphics_shadow_cache_hits"
    const val GRAPHICS_SHADOW_CACHE_MISSES = "graphics_shadow_cache_misses"
    const val GRAPHICS_SHADOW_LAZY_FIRST = "graphics_shadow_lazy_first"
}
