package com.viewcompose.widget.core

import com.viewcompose.text.InputTransformation
import com.viewcompose.text.ReceiveContentConfiguration
import com.viewcompose.text.TextFieldState
import com.viewcompose.ui.modifier.Modifier
import com.viewcompose.ui.modifier.fillMaxWidth
import com.viewcompose.ui.modifier.margin
import com.viewcompose.ui.node.NodeType
import com.viewcompose.ui.node.TextFieldAutofillHint
import com.viewcompose.ui.node.TextFieldImeAction
import com.viewcompose.ui.node.TextFieldKeyboardOptions
import com.viewcompose.ui.node.spec.TextFieldNodeProps
import com.viewcompose.ui.node.spec.uiFontFamily
import com.viewcompose.ui.shape.UiShape

fun UiTreeBuilder.BasicTextField(
    state: TextFieldState,
    hint: String = "",
    placeholder: String = hint,
    enabled: Boolean = true,
    singleLine: Boolean = true,
    readOnly: Boolean = false,
    maxLines: Int = if (singleLine) 1 else Int.MAX_VALUE,
    minLines: Int = if (singleLine) 1 else 1,
    keyboardOptions: TextFieldKeyboardOptions = TextFieldKeyboardOptions(),
    inputTransformation: InputTransformation? = null,
    receiveContent: ReceiveContentConfiguration = ReceiveContentConfiguration.Default,
    onKeyboardAction: ((TextFieldImeAction) -> Boolean)? = null,
    onFocusChange: ((Boolean) -> Unit)? = null,
    autofillHints: Set<TextFieldAutofillHint> = emptySet(),
    cursorColor: Int = TextFieldDefaults.cursorColor(),
    textColor: Int = TextFieldDefaults.textColor(enabled),
    textStyle: UiTextStyle = TextFieldDefaults.textStyle(),
    hintColor: Int = TextFieldDefaults.hintColor(enabled = enabled),
    backgroundColor: Int = 0x00000000,
    borderWidth: Int = 0,
    borderColor: Int = 0x00000000,
    shape: UiShape = UiShape.rounded(0),
    minHeight: Int = 0,
    paddingHorizontal: Int = 0,
    paddingVertical: Int = 0,
    key: Any? = null,
    modifier: Modifier = Modifier,
) {
    emit(
        type = NodeType.TextField,
        key = key,
        spec = basicTextFieldSpec(
            state = state,
            placeholder = placeholder.ifEmpty { hint },
            enabled = enabled,
            singleLine = singleLine,
            minLines = minLines,
            maxLines = maxLines,
            keyboardOptions = keyboardOptions,
            inputTransformation = inputTransformation,
            receiveContent = receiveContent,
            onKeyboardAction = onKeyboardAction,
            onFocusChange = onFocusChange,
            autofillHints = autofillHints,
            hintColor = hintColor,
            readOnly = readOnly,
            textColor = textColor,
            textStyle = textStyle,
            backgroundColor = backgroundColor,
            borderWidth = borderWidth,
            borderColor = borderColor,
            shape = shape,
            minHeight = minHeight,
            paddingHorizontal = paddingHorizontal,
            paddingVertical = paddingVertical,
            cursorColor = cursorColor,
        ),
        modifier = modifier,
    )
}

fun UiTreeBuilder.TextField(
    state: TextFieldState,
    hint: String = "",
    label: String = "",
    placeholder: String = hint,
    supportingText: String = "",
    singleLine: Boolean = true,
    readOnly: Boolean = false,
    maxLines: Int = if (singleLine) 1 else Int.MAX_VALUE,
    minLines: Int = if (singleLine) 1 else 3,
    keyboardOptions: TextFieldKeyboardOptions = TextFieldKeyboardOptions(),
    inputTransformation: InputTransformation? = null,
    receiveContent: ReceiveContentConfiguration = ReceiveContentConfiguration.Default,
    onKeyboardAction: ((TextFieldImeAction) -> Boolean)? = null,
    onFocusChange: ((Boolean) -> Unit)? = null,
    autofillHints: Set<TextFieldAutofillHint> = emptySet(),
    variant: TextFieldVariant = TextFieldVariant.Filled,
    size: TextFieldSize = TextFieldSize.Medium,
    enabled: Boolean = true,
    isError: Boolean = false,
    cursorColor: Int = TextFieldDefaults.cursorColor(),
    style: UiTextStyle = TextFieldDefaults.textStyle(size),
    key: Any? = null,
    modifier: Modifier = Modifier,
) {
    val hintColor = TextFieldDefaults.hintColor(
        enabled = enabled,
        isError = isError,
    )
    val labelColor = TextFieldDefaults.labelColor(
        enabled = enabled,
        isError = isError,
    )
    val supportingTextColor = TextFieldDefaults.supportingTextColor(
        enabled = enabled,
        isError = isError,
    )
    Column(
        key = key,
        modifier = modifier,
    ) {
        if (label.isNotBlank()) {
            Text(
                text = label,
                style = TextFieldDefaults.labelTextStyle(),
                color = labelColor,
                modifier = Modifier.margin(bottom = 4.dp),
            )
        }
        BasicTextField(
            state = state,
            hint = hint,
            placeholder = placeholder.ifEmpty { hint },
            enabled = enabled,
            singleLine = singleLine,
            maxLines = maxLines,
            minLines = minLines,
            keyboardOptions = keyboardOptions,
            inputTransformation = inputTransformation,
            receiveContent = receiveContent,
            onKeyboardAction = onKeyboardAction,
            onFocusChange = onFocusChange,
            autofillHints = autofillHints,
            hintColor = hintColor,
            readOnly = readOnly,
            textColor = TextFieldDefaults.textColor(
                enabled = enabled,
                isError = isError,
            ),
            textStyle = style,
            backgroundColor = TextFieldDefaults.containerColor(
                variant = variant,
                enabled = enabled,
                isError = isError,
            ),
            borderWidth = TextFieldDefaults.borderWidth(variant),
            borderColor = TextFieldDefaults.borderColor(
                variant = variant,
                enabled = enabled,
                isError = isError,
            ),
            shape = TextFieldDefaults.shape(),
            minHeight = if (singleLine) TextFieldDefaults.height(size) else 0,
            paddingHorizontal = TextFieldDefaults.horizontalPadding(size),
            paddingVertical = TextFieldDefaults.verticalPadding(size),
            cursorColor = cursorColor,
            modifier = Modifier.fillMaxWidth(),
        )
        if (supportingText.isNotBlank()) {
            Text(
                text = supportingText,
                style = TextFieldDefaults.supportingTextStyle(),
                color = supportingTextColor,
                modifier = Modifier.margin(top = 4.dp),
            )
        }
    }
}

private fun basicTextFieldSpec(
    state: TextFieldState,
    placeholder: String,
    enabled: Boolean,
    singleLine: Boolean,
    minLines: Int,
    maxLines: Int,
    keyboardOptions: TextFieldKeyboardOptions,
    inputTransformation: InputTransformation?,
    receiveContent: ReceiveContentConfiguration,
    onKeyboardAction: ((TextFieldImeAction) -> Boolean)?,
    onFocusChange: ((Boolean) -> Unit)?,
    autofillHints: Set<TextFieldAutofillHint>,
    hintColor: Int,
    readOnly: Boolean,
    textColor: Int,
    textStyle: UiTextStyle,
    backgroundColor: Int,
    borderWidth: Int,
    borderColor: Int,
    shape: UiShape,
    minHeight: Int,
    paddingHorizontal: Int,
    paddingVertical: Int,
    cursorColor: Int,
): TextFieldNodeProps {
    return TextFieldNodeProps(
        state = state,
        value = state.value,
        placeholder = placeholder,
        enabled = enabled,
        singleLine = singleLine,
        minLines = minLines,
        maxLines = maxLines,
        keyboardOptions = keyboardOptions,
        inputTransformation = inputTransformation,
        receiveContent = receiveContent,
        onKeyboardAction = onKeyboardAction,
        onFocusChange = onFocusChange,
        autofillHints = autofillHints,
        hintColor = hintColor,
        readOnly = readOnly,
        textColor = textColor,
        textSizeSp = textStyle.fontSizeSp,
        fontWeight = textStyle.fontWeight,
        fontFamily = uiFontFamily(textStyle.fontFamily),
        letterSpacingEm = textStyle.letterSpacingEm,
        lineHeightSp = textStyle.lineHeightSp,
        includeFontPadding = textStyle.includeFontPadding,
        backgroundColor = backgroundColor,
        borderWidth = borderWidth,
        borderColor = borderColor,
        shape = shape,
        minHeight = minHeight,
        paddingHorizontal = paddingHorizontal,
        paddingVertical = paddingVertical,
        cursorColor = cursorColor,
    )
}

fun UiTreeBuilder.PasswordField(
    state: TextFieldState,
    hint: String = "",
    label: String = "",
    supportingText: String = "",
    keyboardOptions: TextFieldKeyboardOptions = TextFieldKeyboardOptions(
        keyboardType = com.viewcompose.ui.node.TextFieldType.Password,
        autoCorrectEnabled = false,
    ),
    inputTransformation: InputTransformation? = null,
    receiveContent: ReceiveContentConfiguration = ReceiveContentConfiguration.Default,
    onKeyboardAction: ((TextFieldImeAction) -> Boolean)? = null,
    onFocusChange: ((Boolean) -> Unit)? = null,
    autofillHints: Set<TextFieldAutofillHint> = setOf(TextFieldAutofillHint.Password),
    variant: TextFieldVariant = TextFieldVariant.Filled,
    size: TextFieldSize = TextFieldSize.Medium,
    enabled: Boolean = true,
    isError: Boolean = false,
    style: UiTextStyle = TextFieldDefaults.textStyle(size),
    key: Any? = null,
    modifier: Modifier = Modifier,
) {
    TextField(
        state = state,
        hint = hint,
        label = label,
        supportingText = supportingText,
        singleLine = true,
        keyboardOptions = keyboardOptions,
        inputTransformation = inputTransformation,
        receiveContent = receiveContent,
        onKeyboardAction = onKeyboardAction,
        onFocusChange = onFocusChange,
        autofillHints = autofillHints,
        variant = variant,
        size = size,
        enabled = enabled,
        isError = isError,
        style = style,
        key = key,
        modifier = modifier,
    )
}

fun UiTreeBuilder.EmailField(
    state: TextFieldState,
    hint: String = "",
    label: String = "",
    supportingText: String = "",
    keyboardOptions: TextFieldKeyboardOptions = TextFieldKeyboardOptions(
        keyboardType = com.viewcompose.ui.node.TextFieldType.Email,
    ),
    inputTransformation: InputTransformation? = null,
    receiveContent: ReceiveContentConfiguration = ReceiveContentConfiguration.Default,
    onKeyboardAction: ((TextFieldImeAction) -> Boolean)? = null,
    onFocusChange: ((Boolean) -> Unit)? = null,
    autofillHints: Set<TextFieldAutofillHint> = setOf(TextFieldAutofillHint.EmailAddress),
    variant: TextFieldVariant = TextFieldVariant.Filled,
    size: TextFieldSize = TextFieldSize.Medium,
    enabled: Boolean = true,
    style: UiTextStyle = TextFieldDefaults.textStyle(size),
    key: Any? = null,
    modifier: Modifier = Modifier,
) {
    TextField(
        state = state,
        hint = hint,
        label = label,
        supportingText = supportingText,
        singleLine = true,
        keyboardOptions = keyboardOptions,
        inputTransformation = inputTransformation,
        receiveContent = receiveContent,
        onKeyboardAction = onKeyboardAction,
        onFocusChange = onFocusChange,
        autofillHints = autofillHints,
        variant = variant,
        size = size,
        enabled = enabled,
        style = style,
        key = key,
        modifier = modifier,
    )
}

fun UiTreeBuilder.NumberField(
    state: TextFieldState,
    hint: String = "",
    label: String = "",
    supportingText: String = "",
    keyboardOptions: TextFieldKeyboardOptions = TextFieldKeyboardOptions(
        keyboardType = com.viewcompose.ui.node.TextFieldType.Number,
        autoCorrectEnabled = false,
    ),
    inputTransformation: InputTransformation? = null,
    receiveContent: ReceiveContentConfiguration = ReceiveContentConfiguration.Default,
    onKeyboardAction: ((TextFieldImeAction) -> Boolean)? = null,
    onFocusChange: ((Boolean) -> Unit)? = null,
    autofillHints: Set<TextFieldAutofillHint> = emptySet(),
    variant: TextFieldVariant = TextFieldVariant.Filled,
    size: TextFieldSize = TextFieldSize.Medium,
    enabled: Boolean = true,
    style: UiTextStyle = TextFieldDefaults.textStyle(size),
    key: Any? = null,
    modifier: Modifier = Modifier,
) {
    TextField(
        state = state,
        hint = hint,
        label = label,
        supportingText = supportingText,
        singleLine = true,
        keyboardOptions = keyboardOptions,
        inputTransformation = inputTransformation,
        receiveContent = receiveContent,
        onKeyboardAction = onKeyboardAction,
        onFocusChange = onFocusChange,
        autofillHints = autofillHints,
        variant = variant,
        size = size,
        enabled = enabled,
        style = style,
        key = key,
        modifier = modifier,
    )
}

fun UiTreeBuilder.TextArea(
    state: TextFieldState,
    hint: String = "",
    label: String = "",
    placeholder: String = hint,
    supportingText: String = "",
    variant: TextFieldVariant = TextFieldVariant.Filled,
    size: TextFieldSize = TextFieldSize.Medium,
    enabled: Boolean = true,
    isError: Boolean = false,
    readOnly: Boolean = false,
    minLines: Int = 3,
    maxLines: Int = Int.MAX_VALUE,
    keyboardOptions: TextFieldKeyboardOptions = TextFieldKeyboardOptions(),
    inputTransformation: InputTransformation? = null,
    receiveContent: ReceiveContentConfiguration = ReceiveContentConfiguration.Default,
    onKeyboardAction: ((TextFieldImeAction) -> Boolean)? = null,
    onFocusChange: ((Boolean) -> Unit)? = null,
    autofillHints: Set<TextFieldAutofillHint> = emptySet(),
    style: UiTextStyle = TextFieldDefaults.textStyle(size),
    key: Any? = null,
    modifier: Modifier = Modifier,
) {
    TextField(
        state = state,
        hint = hint,
        label = label,
        placeholder = placeholder,
        supportingText = supportingText,
        singleLine = false,
        readOnly = readOnly,
        maxLines = maxLines,
        minLines = minLines,
        keyboardOptions = keyboardOptions,
        inputTransformation = inputTransformation,
        receiveContent = receiveContent,
        onKeyboardAction = onKeyboardAction,
        onFocusChange = onFocusChange,
        autofillHints = autofillHints,
        variant = variant,
        size = size,
        enabled = enabled,
        isError = isError,
        style = style,
        key = key,
        modifier = modifier,
    )
}
